apiVersion: v1
kind: Pod
metadata:
  name: liveness-http
  labels:
    name: liveness-http
spec:
  containers:
  - name: liveness
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    livenessProbe:
      httpGet:
        path: /main
        port: 80
      initialDelaySeconds: 10
      timeoutSeconds: 2
      periodSeconds: 5