apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: mynginx
    image: nginx:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"