apiVersion: v1
kind: Pod
metadata:
  name: never-pod
  labels:
    app: restart_policy
spec:
  restartPolicy: Always
  containers:
  - name: busybox
    image: busybox
    command: ['sh','-c','sleep 10;this will fail']
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
