apiVersion: v1
kind: Pod
metadata:
  name: secpo
  labels:
    name: secpo
spec:
  containers:
  - name: secpo
    image: nginx:alpine
    command: ['sh','-c','sleep 3600']
    args: ["-c", "while true; do echo hello; sleep 10;done"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
