apiVersion: v1
kind: Pod
metadata:
  name: big-request
spec:
  containers:
  - name: busy-box
    image: busybox
    command: ['sh','-c','while true; do sleep 3600;done']
    resources:
      requests:
        cpu: "10000m"
        memory: "128Mi"